//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Address represents an IPv4 or IPv6 IP address. */
public struct Address: Codable, JSONEncodable, Hashable {

    /** IP address. */
    public var addr: String?
    /** Mask length of the IP address. */
    public var prefixLen: Int?

    public init(addr: String? = nil, prefixLen: Int? = nil) {
        self.addr = addr
        self.prefixLen = prefixLen
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addr = "Addr"
        case prefixLen = "PrefixLen"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addr, forKey: .addr)
        try container.encodeIfPresent(prefixLen, forKey: .prefixLen)
    }
}

