//
// ClusterVolumeSpecAccessModeCapacityRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The desired capacity that the volume should be created with. If empty, the plugin will decide the capacity.  */
public struct ClusterVolumeSpecAccessModeCapacityRange: Codable, JSONEncodable, Hashable {

    /** The volume must be at least this big. The value of 0 indicates an unspecified minimum  */
    public var requiredBytes: Int64?
    /** The volume must not be bigger than this. The value of 0 indicates an unspecified maximum.  */
    public var limitBytes: Int64?

    public init(requiredBytes: Int64? = nil, limitBytes: Int64? = nil) {
        self.requiredBytes = requiredBytes
        self.limitBytes = limitBytes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requiredBytes = "RequiredBytes"
        case limitBytes = "LimitBytes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(requiredBytes, forKey: .requiredBytes)
        try container.encodeIfPresent(limitBytes, forKey: .limitBytes)
    }
}

