//
// Commit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Commit holds the Git-commit (SHA1) that a binary was built from, as reported in the version-string of external tools, such as &#x60;containerd&#x60;, or &#x60;runC&#x60;.  */
public struct Commit: Codable, JSONEncodable, Hashable {

    /** Actual commit ID of external tool. */
    public var ID: String?
    /** Commit ID of external tool expected by dockerd as set at build time.  */
    public var expected: String?

    public init(ID: String? = nil, expected: String? = nil) {
        self.ID = ID
        self.expected = expected
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case expected = "Expected"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ID, forKey: .ID)
        try container.encodeIfPresent(expected, forKey: .expected)
    }
}

