//
// ContainerChangeResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** change item in response to ContainerChanges operation */
public struct ContainerChangeResponseItem: Codable, JSONEncodable, Hashable {

    /** Path to file that has changed */
    public var path: String
    /** Kind of change */
    public var kind: Int

    public init(path: String, kind: Int) {
        self.path = path
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case kind = "Kind"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encode(kind, forKey: .kind)
    }
}

