//
// ContainerCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OK response to ContainerCreate operation */
public struct ContainerCreateResponse: Codable, JSONEncodable, Hashable {

    /** The ID of the created container */
    public var id: String
    /** Warnings encountered when creating the container */
    public var warnings: [String]

    public init(id: String, warnings: [String]) {
        self.id = id
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case warnings = "Warnings"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(warnings, forKey: .warnings)
    }
}

