//
// ContainerTopResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OK response to ContainerTop operation */
public struct ContainerTopResponse: Codable, JSONEncodable, Hashable {

    /** The ps column titles */
    public var titles: [String]?
    /** Each process running in the container, where each is process is an array of values corresponding to the titles.  */
    public var processes: [[String]]?

    public init(titles: [String]? = nil, processes: [[String]]? = nil) {
        self.titles = titles
        self.processes = processes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case titles = "Titles"
        case processes = "Processes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(titles, forKey: .titles)
        try container.encodeIfPresent(processes, forKey: .processes)
    }
}

