//
// ContainerCreateRequestAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContainerCreateRequestAllOf: Codable, JSONEncodable, Hashable {

    public var hostConfig: HostConfig?
    public var networkingConfig: NetworkingConfig?

    public init(hostConfig: HostConfig? = nil, networkingConfig: NetworkingConfig? = nil) {
        self.hostConfig = hostConfig
        self.networkingConfig = networkingConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hostConfig = "HostConfig"
        case networkingConfig = "NetworkingConfig"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hostConfig, forKey: .hostConfig)
        try container.encodeIfPresent(networkingConfig, forKey: .networkingConfig)
    }
}

