//
// Driver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Driver represents a driver (network, logging, secrets). */
public struct Driver: Codable, JSONEncodable, Hashable {

    /** Name of the driver. */
    public var name: String
    /** Key/value map of driver-specific options. */
    public var options: [String: String]?

    public init(name: String, options: [String: String]? = nil) {
        self.name = name
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case options = "Options"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(options, forKey: .options)
    }
}

