//
// EndpointIPAMConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** EndpointIPAMConfig represents an endpoint&#39;s IPAM configuration.  */
public struct EndpointIPAMConfig: Codable, JSONEncodable, Hashable {

    public var iPv4Address: String?
    public var iPv6Address: String?
    public var linkLocalIPs: [String]?

    public init(iPv4Address: String? = nil, iPv6Address: String? = nil, linkLocalIPs: [String]? = nil) {
        self.iPv4Address = iPv4Address
        self.iPv6Address = iPv6Address
        self.linkLocalIPs = linkLocalIPs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iPv4Address = "IPv4Address"
        case iPv6Address = "IPv6Address"
        case linkLocalIPs = "LinkLocalIPs"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iPv4Address, forKey: .iPv4Address)
        try container.encodeIfPresent(iPv6Address, forKey: .iPv6Address)
        try container.encodeIfPresent(linkLocalIPs, forKey: .linkLocalIPs)
    }
}

