//
// ExecStartConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExecStartConfig: Codable, JSONEncodable, Hashable {

    /** Detach from the command. */
    public var detach: Bool?
    /** Allocate a pseudo-TTY. */
    public var tty: Bool?
    /** Initial console size, as an `[height, width]` array. */
    public var consoleSize: [Int]?

    public init(detach: Bool? = nil, tty: Bool? = nil, consoleSize: [Int]? = nil) {
        self.detach = detach
        self.tty = tty
        self.consoleSize = consoleSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case detach = "Detach"
        case tty = "Tty"
        case consoleSize = "ConsoleSize"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(detach, forKey: .detach)
        try container.encodeIfPresent(tty, forKey: .tty)
        try container.encodeIfPresent(consoleSize, forKey: .consoleSize)
    }
}

