//
// GraphDriverData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Information about the storage driver used to store the container&#39;s and image&#39;s filesystem.  */
public struct GraphDriverData: Codable, JSONEncodable, Hashable {

    /** Name of the storage driver. */
    public var name: String
    /** Low-level storage metadata, provided as key/value pairs.  This information is driver-specific, and depends on the storage-driver in use, and should be used for informational purposes only.  */
    public var data: [String: String]

    public init(name: String, data: [String: String]) {
        self.name = name
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case data = "Data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(data, forKey: .data)
    }
}

