//
// HostConfigAllOfLogConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The logging configuration for this container */
public struct HostConfigAllOfLogConfig: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case jsonFile = "json-file"
        case syslog = "syslog"
        case journald = "journald"
        case gelf = "gelf"
        case fluentd = "fluentd"
        case awslogs = "awslogs"
        case splunk = "splunk"
        case etwlogs = "etwlogs"
        case _none = "none"
    }
    public var type: ModelType?
    public var config: [String: String]?

    public init(type: ModelType? = nil, config: [String: String]? = nil) {
        self.type = type
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case config = "Config"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

