//
// ImageInspectMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Additional metadata of the image in the local cache. This information is local to the daemon, and not part of the image itself.  */
public struct ImageInspectMetadata: Codable, JSONEncodable, Hashable {

    /** Date and time at which the image was last tagged in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  This information is only available if the image was tagged locally, and omitted otherwise.  */
    public var lastTagTime: String?

    public init(lastTagTime: String? = nil) {
        self.lastTagTime = lastTagTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lastTagTime = "LastTagTime"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lastTagTime, forKey: .lastTagTime)
    }
}

