//
// ImageDeleteResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImageDeleteResponseItem: Codable, JSONEncodable, Hashable {

    /** The image ID of an image that was untagged */
    public var untagged: String?
    /** The image ID of an image that was deleted */
    public var deleted: String?

    public init(untagged: String? = nil, deleted: String? = nil) {
        self.untagged = untagged
        self.deleted = deleted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case untagged = "Untagged"
        case deleted = "Deleted"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(untagged, forKey: .untagged)
        try container.encodeIfPresent(deleted, forKey: .deleted)
    }
}

