//
// ImagePruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImagePruneResponse: Codable, JSONEncodable, Hashable {

    /** Images that were deleted */
    public var imagesDeleted: [ImageDeleteResponseItem]?
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int64?

    public init(imagesDeleted: [ImageDeleteResponseItem]? = nil, spaceReclaimed: Int64? = nil) {
        self.imagesDeleted = imagesDeleted
        self.spaceReclaimed = spaceReclaimed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imagesDeleted = "ImagesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imagesDeleted, forKey: .imagesDeleted)
        try container.encodeIfPresent(spaceReclaimed, forKey: .spaceReclaimed)
    }
}

