//
// ImageSearchResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImageSearchResponseItem: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var isOfficial: Bool?
    public var isAutomated: Bool?
    public var name: String?
    public var starCount: Int?

    public init(description: String? = nil, isOfficial: Bool? = nil, isAutomated: Bool? = nil, name: String? = nil, starCount: Int? = nil) {
        self.description = description
        self.isOfficial = isOfficial
        self.isAutomated = isAutomated
        self.name = name
        self.starCount = starCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case isOfficial = "is_official"
        case isAutomated = "is_automated"
        case name
        case starCount = "star_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isOfficial, forKey: .isOfficial)
        try container.encodeIfPresent(isAutomated, forKey: .isAutomated)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(starCount, forKey: .starCount)
    }
}

