//
// PluginPrivilege.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Describes a permission the user has to accept upon installing the plugin.  */
public struct PluginPrivilege: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var value: [String]?

    public init(name: String? = nil, description: String? = nil, value: [String]? = nil) {
        self.name = name
        self.description = description
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case description = "Description"
        case value = "Value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

