//
// PluginSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Settings that can be modified by users. */
public struct PluginSettings: Codable, JSONEncodable, Hashable {

    public var mounts: [PluginMount]
    public var env: [String]
    public var args: [String]
    public var devices: [PluginDevice]

    public init(mounts: [PluginMount], env: [String], args: [String], devices: [PluginDevice]) {
        self.mounts = mounts
        self.env = env
        self.args = args
        self.devices = devices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mounts = "Mounts"
        case env = "Env"
        case args = "Args"
        case devices = "Devices"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mounts, forKey: .mounts)
        try container.encode(env, forKey: .env)
        try container.encode(args, forKey: .args)
        try container.encode(devices, forKey: .devices)
    }
}

