//
// ProcessConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcessConfig: Codable, JSONEncodable, Hashable {

    public var privileged: Bool?
    public var user: String?
    public var tty: Bool?
    public var entrypoint: String?
    public var arguments: [String]?

    public init(privileged: Bool? = nil, user: String? = nil, tty: Bool? = nil, entrypoint: String? = nil, arguments: [String]? = nil) {
        self.privileged = privileged
        self.user = user
        self.tty = tty
        self.entrypoint = entrypoint
        self.arguments = arguments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case privileged
        case user
        case tty
        case entrypoint
        case arguments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(privileged, forKey: .privileged)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(tty, forKey: .tty)
        try container.encodeIfPresent(entrypoint, forKey: .entrypoint)
        try container.encodeIfPresent(arguments, forKey: .arguments)
    }
}

