//
// ProgressDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProgressDetail: Codable, JSONEncodable, Hashable {

    public var current: Int?
    public var total: Int?

    public init(current: Int? = nil, total: Int? = nil) {
        self.current = current
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

