//
// ResourcesUlimitsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResourcesUlimitsInner: Codable, JSONEncodable, Hashable {

    /** Name of ulimit */
    public var name: String?
    /** Soft limit */
    public var soft: Int?
    /** Hard limit */
    public var hard: Int?

    public init(name: String? = nil, soft: Int? = nil, hard: Int? = nil) {
        self.name = name
        self.soft = soft
        self.hard = hard
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case soft = "Soft"
        case hard = "Hard"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(soft, forKey: .soft)
        try container.encodeIfPresent(hard, forKey: .hard)
    }
}

