//
// ServiceEndpointVirtualIPsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceEndpointVirtualIPsInner: Codable, JSONEncodable, Hashable {

    public var networkID: String?
    public var addr: String?

    public init(networkID: String? = nil, addr: String? = nil) {
        self.networkID = networkID
        self.addr = addr
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networkID = "NetworkID"
        case addr = "Addr"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(networkID, forKey: .networkID)
        try container.encodeIfPresent(addr, forKey: .addr)
    }
}

