//
// ServiceJobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status of the service when it is in one of ReplicatedJob or GlobalJob modes. Absent on Replicated and Global mode services. The JobIteration is an ObjectVersion, but unlike the Service&#39;s version, does not need to be sent with an update request.  */
public struct ServiceJobStatus: Codable, JSONEncodable, Hashable {

    public var jobIteration: ObjectVersion?
    /** The last time, as observed by the server, that this job was started.  */
    public var lastExecution: String?

    public init(jobIteration: ObjectVersion? = nil, lastExecution: String? = nil) {
        self.jobIteration = jobIteration
        self.lastExecution = lastExecution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobIteration = "JobIteration"
        case lastExecution = "LastExecution"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(jobIteration, forKey: .jobIteration)
        try container.encodeIfPresent(lastExecution, forKey: .lastExecution)
    }
}

