//
// ServiceUpdateStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status of a service update. */
public struct ServiceUpdateStatus: Codable, JSONEncodable, Hashable {

    public enum State: String, Codable, CaseIterable {
        case updating = "updating"
        case paused = "paused"
        case completed = "completed"
    }
    public var state: State?
    public var startedAt: String?
    public var completedAt: String?
    public var message: String?

    public init(state: State? = nil, startedAt: String? = nil, completedAt: String? = nil, message: String? = nil) {
        self.state = state
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case state = "State"
        case startedAt = "StartedAt"
        case completedAt = "CompletedAt"
        case message = "Message"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

