//
// SwarmSpecTaskDefaultsLogDriver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The log driver to use for tasks created in the orchestrator if unspecified by a service.  Updating this value only affects new tasks. Existing tasks continue to use their previously configured log driver until recreated.  */
public struct SwarmSpecTaskDefaultsLogDriver: Codable, JSONEncodable, Hashable {

    /** The log driver to use as a default for new tasks.  */
    public var name: String?
    /** Driver-specific options for the selectd log driver, specified as key/value pairs.  */
    public var options: [String: String]?

    public init(name: String? = nil, options: [String: String]? = nil) {
        self.name = name
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case options = "Options"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(options, forKey: .options)
    }
}

