//
// SwarmAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SwarmAllOf: Codable, JSONEncodable, Hashable {

    public var joinTokens: JoinTokens?

    public init(joinTokens: JoinTokens? = nil) {
        self.joinTokens = joinTokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case joinTokens = "JoinTokens"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(joinTokens, forKey: .joinTokens)
    }
}

