//
// SystemVersionComponentsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemVersionComponentsInner: Codable, JSONEncodable, Hashable {

    /** Name of the component  */
    public var name: String
    /** Version of the component  */
    public var version: String
    /** Key/value pairs of strings with additional information about the component. These values are intended for informational purposes only, and their content is not defined, and not part of the API specification.  These messages can be printed by the client as information to the user.  */
    public var details: AnyCodable?

    public init(name: String, version: String, details: AnyCodable? = nil) {
        self.name = name
        self.version = version
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case version = "Version"
        case details = "Details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(version, forKey: .version)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

