//
// TaskStatusContainerStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaskStatusContainerStatus: Codable, JSONEncodable, Hashable {

    public var containerID: String?
    public var PID: Int?
    public var exitCode: Int?

    public init(containerID: String? = nil, PID: Int? = nil, exitCode: Int? = nil) {
        self.containerID = containerID
        self.PID = PID
        self.exitCode = exitCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case containerID = "ContainerID"
        case PID
        case exitCode = "ExitCode"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(containerID, forKey: .containerID)
        try container.encodeIfPresent(PID, forKey: .PID)
        try container.encodeIfPresent(exitCode, forKey: .exitCode)
    }
}

