//
// TaskStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaskStatus: Codable, JSONEncodable, Hashable {

    public var timestamp: String?
    public var state: TaskState?
    public var message: String?
    public var err: String?
    public var containerStatus: TaskStatusContainerStatus?

    public init(timestamp: String? = nil, state: TaskState? = nil, message: String? = nil, err: String? = nil, containerStatus: TaskStatusContainerStatus? = nil) {
        self.timestamp = timestamp
        self.state = state
        self.message = message
        self.err = err
        self.containerStatus = containerStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp = "Timestamp"
        case state = "State"
        case message = "Message"
        case err = "Err"
        case containerStatus = "ContainerStatus"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(err, forKey: .err)
        try container.encodeIfPresent(containerStatus, forKey: .containerStatus)
    }
}

