//
// TaskSpecPlacementPreferencesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaskSpecPlacementPreferencesInner: Codable, JSONEncodable, Hashable {

    public var spread: TaskSpecPlacementPreferencesInnerSpread?

    public init(spread: TaskSpecPlacementPreferencesInnerSpread? = nil) {
        self.spread = spread
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case spread = "Spread"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(spread, forKey: .spread)
    }
}

