//
// TaskState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TaskState: String, Codable, CaseIterable {
    case new = "new"
    case allocated = "allocated"
    case pending = "pending"
    case assigned = "assigned"
    case accepted = "accepted"
    case preparing = "preparing"
    case ready = "ready"
    case starting = "starting"
    case running = "running"
    case complete = "complete"
    case shutdown = "shutdown"
    case failed = "failed"
    case rejected = "rejected"
    case remove = "remove"
    case orphaned = "orphaned"
}
