//
// VolumeListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Volume list response */
public struct VolumeListResponse: Codable, JSONEncodable, Hashable {

    /** List of volumes */
    public var volumes: [Volume]?
    /** Warnings that occurred when fetching the list of volumes.  */
    public var warnings: [String]?

    public init(volumes: [Volume]? = nil, warnings: [String]? = nil) {
        self.volumes = volumes
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case volumes = "Volumes"
        case warnings = "Warnings"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(volumes, forKey: .volumes)
        try container.encodeIfPresent(warnings, forKey: .warnings)
    }
}

