//
// VolumePruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VolumePruneResponse: Codable, JSONEncodable, Hashable {

    /** Volumes that were deleted */
    public var volumesDeleted: [String]?
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int64?

    public init(volumesDeleted: [String]? = nil, spaceReclaimed: Int64? = nil) {
        self.volumesDeleted = volumesDeleted
        self.spaceReclaimed = spaceReclaimed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case volumesDeleted = "VolumesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(volumesDeleted, forKey: .volumesDeleted)
        try container.encodeIfPresent(spaceReclaimed, forKey: .spaceReclaimed)
    }
}

